### ISSUE TITLE
IOError when file does not exist (yet)

### ISSUE THREAD

**Issue by alfredodeza** [garybernhardt/pycomplexity#8]
When editing a new file Python will raise an IOError and it will fill the Messages window with errors similar to this:

```
Error detected while processing function <SNR>37_ShowComplexity:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 163, in show_complexity
  File "<string>", line 175, in compute_scores_for
IOError: [Errno 2] No such file or directory: '/opt/devel/cms_dev/src/conf/foo.py'
```

Easy fix, but prefer to report it before I forget about it. I can send a pull request with a fix in the next week or so unless you beat me to it.

**Comment by garybernhardt** [comment]
I almost never write Python right now, so I'm probably not going to beat you to it, but a PR would be appreciated. :)
